### ISSUE TITLE
Standard-/Vaadin-conform public API

### ISSUE THREAD

**Issue by kevinkendzia** [xdev-software/vaadin-chip-combobox#12]
The fluent-"with"-methods of the ChipCombobox class are nice to build a fully configured combobox in one line of code, but I think we are missing the default setters.
Especially if you're setting single values dynamically, a setter in the form "setXYZ" more clear than "withXYZ". Also the first method I search for to set a value is a default setter.

```java
// Current
cbo.withLabel("TEST");

// request
cbo.setLabel("TEST");
```

Please ADD default setters (don't remove the "with"-Setter)

Also for the withAllAvailableItems()-methods consider renaming (at least the default setter) to just "setItems()" and implement the Vaadin-Interface HasItems to be Vaadin-conform.

**Comment by AB-xdev** [comment]
Todo:
* Create setters
* Add ``HasItems`` interface

**Comment by AB-xdev** [comment]
Will be further improved with v2 / #25 / #24
