### ISSUE TITLE
Make ItemLabelGenerator customizable

### ISSUE THREAD

**Issue by kevinkendzia** [xdev-software/vaadin-chip-combobox#13]
Currently the ChipCombobox uses a hard coded ItemLabelGenerator which uses Object::toString to render the text of the chips.
This way the used object in the combobox has to override the toString()-method to change the displayed text.

It would be nice to have a setter for the ItemLabelGenerator like every other Vaadin-component with items to change the rendered text of an Chip:

```java
ChipCombobox<TestDTO> cbo = new ChipCombobox<>();
cbo.setItemLabelGenerator(TestDTO::getDisplayProperty);
```

Also consider implementing delegate setters for the internal Combobox to make it easier to set its ItemLabelGenerator and possibly its Renderer too.

```java
ChipCombobox<TestDTO> cbo = new ChipCombobox<>();
cbo.setComboboxItemLabelGenerator(TestDTO::getDisplayProperty);
cbo.setComboboxRenderer(new TextRenderer<>(TestDTO::getDisplayProperty));
cbo.setChipItemLabelGenerator(TestDTO::getDisplayProperty);
```

**Comment by AB-xdev** [comment]
Todo: Add missing setter/with-Method and getter

**Comment by mh-xdev** [comment]
I'll be working on this issue
