### ISSUE TITLE
Implement HasValidation on ChipComboBox 

### ISSUE THREAD

**Issue by kevinkendzia** [xdev-software/vaadin-chip-combobox#49]
Right now the ChipComboBox does not implement com.vaadin.flow.component.HasValidation and because of that it does not show any error indicator (red frame, red message below the component) when it gets validated by a binder.

Like that it differs from other components on the page, that reduces the UX.

As a simple solution the ChipComboBox could implement the interface com.vaadin.flow.component.HasValidation and forward the methods to the contained ComboBox.

A more advanced possibility would be to extend CustomField instead of AbstractField. Like this the error text would be shown below the "Chips". For this also the implementation of setLabel() should be changed, because CustomField contains a Label by itself so the the Label of the contained ComboBox isn't needed.

**Comment by AB-xdev** [comment]
Fix: Pass through to the Combobox

![grafik](https://user-images.githubusercontent.com/45384811/133968024-590b116c-5f46-4b25-af19-1ad6f8d45aaa.png)
